export const records = [
    { value: 'geo_id', label: 'Geographic Information', },
    { value: 'interview_record', label: 'Interview Record', },
    { value: 'section_a', label: 'Section A', },
    { value: 'section_b', label: 'Section B', },
    { value: 'section_c', label: 'Section C', },
    { value: 'section_d', label: 'Section D', },
    { value: 'section_e', label: 'Section E', },
    { value: 'section_f', label: 'Section F', },
    { value: 'section_f1', label: 'Section F1', },
    { value: 'section_g_new', label: 'Section G', },
    { value: 'section_g1_new', label: 'Section G1', },
    { value: 'section_h', label: 'Section H', },
    { value: 'section_h1', label: 'Section H1', },
    { value: 'section_i', label: 'Section I', },
    { value: 'section_j', label: 'Section J', },
    { value: 'section_k', label: 'Section K', },
    { value: 'section_l', label: 'Section L', },
    { value: 'section_l1', label: 'Section L1', },
    { value: 'section_m', label: 'Section M', },
    { value: 'section_n', label: 'Section N', },
    { value: 'section_o', label: 'Section O', },
    { value: 'section_o1', label: 'Section O1', },
    { value: 'section_p', label: 'Section P', },
    { value: 'section_p1', label: 'Section P1', },
    { value: 'section_q', label: 'Section Q', },
    { value: 'section_r', label: 'Section R', },
    { value: 'section_s', label: 'Section S', },
    { value: 'summary_of_visit', label: 'Summary of Visit', },
]
