hpq$section_o$o01_safewalk_fct <- factor(hpq$section_o$o01_safewalk,levels = c(1,2,3,4,5,8),labels = c("1 - SAFE","2 - SOMEWHAT SAFE","3 - SOMEWHAT UNSAFE","4 - UNSAFE","5 - I'M AFRAID TO BE ALONE","8 - DON'T KNOW"))
hpq$section_o$o02_victim_fct <- factor(hpq$section_o$o02_victim,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_o$o03a_theft_fct <- factor(hpq$section_o$o03a_theft,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_o$o03b_robbery_fct <- factor(hpq$section_o$o03b_robbery,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_o$o03c_asthreat_fct <- factor(hpq$section_o$o03c_asthreat,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_o$o03d_violence_fct <- factor(hpq$section_o$o03d_violence,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_o$o03e_sxoff_fct <- factor(hpq$section_o$o03e_sxoff,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_o$o03f_fraud_fct <- factor(hpq$section_o$o03f_fraud,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_o$o03g_corrupt_fct <- factor(hpq$section_o$o03g_corrupt,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_o$o03i_vehtheft_fct <- factor(hpq$section_o$o03i_vehtheft,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_o$o03j_housbreak_fct <- factor(hpq$section_o$o03j_housbreak,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_o$o03k_vandalism_fct <- factor(hpq$section_o$o03k_vandalism,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_o$o03z_oth_fct <- factor(hpq$section_o$o03z_oth,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))

hpq$section_o1$o06a_theft_fct <- factor(hpq$section_o1$o06a_theft,levels = c(1,2,3,4),labels = c("1 - WITHIN THE BARANGAY","2 - OUTSIDE THE BARANGAY BUT WITHIN MUNICIPALITY/CITY","3 - OUTSIDE THE MUNICIPALITY/CITY BUT WITHIN PROVINCE","4 - OUTSIDE THE PROVINCE"))
hpq$section_o1$o06b_robbery_fct <- factor(hpq$section_o1$o06b_robbery,levels = c(1,2,3,4),labels = c("1 - WITHIN THE BARANGAY","2 - OUTSIDE THE BARANGAY BUT WITHIN MUNICIPALITY/CITY","3 - OUTSIDE THE MUNICIPALITY/CITY BUT WITHIN PROVINCE","4 - OUTSIDE THE PROVINCE"))
hpq$section_o1$o06c_asthreat_fct <- factor(hpq$section_o1$o06c_asthreat,levels = c(1,2,3,4),labels = c("1 - WITHIN THE BARANGAY","2 - OUTSIDE THE BARANGAY BUT WITHIN MUNICIPALITY/CITY","3 - OUTSIDE THE MUNICIPALITY/CITY BUT WITHIN PROVINCE","4 - OUTSIDE THE PROVINCE"))
hpq$section_o1$o06d_violence_fct <- factor(hpq$section_o1$o06d_violence,levels = c(1,2,3,4),labels = c("1 - WITHIN THE BARANGAY","2 - OUTSIDE THE BARANGAY BUT WITHIN MUNICIPALITY/CITY","3 - OUTSIDE THE MUNICIPALITY/CITY BUT WITHIN PROVINCE","4 - OUTSIDE THE PROVINCE"))
hpq$section_o1$o06e_sxoff_fct <- factor(hpq$section_o1$o06e_sxoff,levels = c(1,2,3,4),labels = c("1 - WITHIN THE BARANGAY","2 - OUTSIDE THE BARANGAY BUT WITHIN MUNICIPALITY/CITY","3 - OUTSIDE THE MUNICIPALITY/CITY BUT WITHIN PROVINCE","4 - OUTSIDE THE PROVINCE"))
hpq$section_o1$o06f_fraud_fct <- factor(hpq$section_o1$o06f_fraud,levels = c(1,2,3,4),labels = c("1 - WITHIN THE BARANGAY","2 - OUTSIDE THE BARANGAY BUT WITHIN MUNICIPALITY/CITY","3 - OUTSIDE THE MUNICIPALITY/CITY BUT WITHIN PROVINCE","4 - OUTSIDE THE PROVINCE"))
hpq$section_o1$o06g_corrupt_fct <- factor(hpq$section_o1$o06g_corrupt,levels = c(1,2,3,4),labels = c("1 - WITHIN THE BARANGAY","2 - OUTSIDE THE BARANGAY BUT WITHIN MUNICIPALITY/CITY","3 - OUTSIDE THE MUNICIPALITY/CITY BUT WITHIN PROVINCE","4 - OUTSIDE THE PROVINCE"))
hpq$section_o1$o06i_vehtheft_fct <- factor(hpq$section_o1$o06i_vehtheft,levels = c(1,2,3,4),labels = c("1 - WITHIN THE BARANGAY","2 - OUTSIDE THE BARANGAY BUT WITHIN MUNICIPALITY/CITY","3 - OUTSIDE THE MUNICIPALITY/CITY BUT WITHIN PROVINCE","4 - OUTSIDE THE PROVINCE"))
hpq$section_o1$o06j_housbreak_fct <- factor(hpq$section_o1$o06j_housbreak,levels = c(1),labels = c("1 - WITHIN THE BARANGAY"))
hpq$section_o1$o06k_vandalism_fct <- factor(hpq$section_o1$o06k_vandalism,levels = c(1,2,3,4),labels = c("1 - WITHIN THE BARANGAY","2 - OUTSIDE THE BARANGAY BUT WITHIN MUNICIPALITY/CITY","3 - OUTSIDE THE MUNICIPALITY/CITY BUT WITHIN PROVINCE","4 - OUTSIDE THE PROVINCE"))
hpq$section_o1$o06z_oth_fct <- factor(hpq$section_o1$o06z_oth,levels = c(1,2,3,4),labels = c("1 - WITHIN THE BARANGAY","2 - OUTSIDE THE BARANGAY BUT WITHIN MUNICIPALITY/CITY","3 - OUTSIDE THE MUNICIPALITY/CITY BUT WITHIN PROVINCE","4 - OUTSIDE THE PROVINCE"))
hpq$section_o1$o07a_theft_fct <- factor(hpq$section_o1$o07a_theft,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_o1$o07b_robbery_fct <- factor(hpq$section_o1$o07b_robbery,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_o1$o07c_asthreat_fct <- factor(hpq$section_o1$o07c_asthreat,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_o1$o07d_violence_fct <- factor(hpq$section_o1$o07d_violence,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_o1$o07e_sxoff_fct <- factor(hpq$section_o1$o07e_sxoff,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_o1$o07f_fraud_fct <- factor(hpq$section_o1$o07f_fraud,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_o1$o07g_corrupt_fct <- factor(hpq$section_o1$o07g_corrupt,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_o1$o07i_vehtheft_fct <- factor(hpq$section_o1$o07i_vehtheft,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_o1$o07j_housbreak_fct <- factor(hpq$section_o1$o07j_housbreak,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_o1$o07k_vandalism_fct <- factor(hpq$section_o1$o07k_vandalism,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_o1$o07z_oth_fct <- factor(hpq$section_o1$o07z_oth,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_o1$o08a_theft_fct <- factor(hpq$section_o1$o08a_theft,levels = c(1,2,3,4,5,9),labels = c("1 - THREATENED","2 - AFRAID","3 - NO FINANCIAL SUPPORT","4 - THINKS NO ONE WOULD LISTEN/BELIEVE","5 - EMBARRASSED/ASHAMED","9 - OTHERS, SPECIFY:____"))
hpq$section_o1$o08b_robbery_fct <- factor(hpq$section_o1$o08b_robbery,levels = c(1,2,3,4,5,9),labels = c("1 - THREATENED","2 - AFRAID","3 - NO FINANCIAL SUPPORT","4 - THINKS NO ONE WOULD LISTEN/BELIEVE","5 - EMBARRASSED/ASHAMED","9 - OTHERS, SPECIFY:____"))
hpq$section_o1$o08c_asthreat_fct <- factor(hpq$section_o1$o08c_asthreat,levels = c(1,2,3,4,5,9),labels = c("1 - THREATENED","2 - AFRAID","3 - NO FINANCIAL SUPPORT","4 - THINKS NO ONE WOULD LISTEN/BELIEVE","5 - EMBARRASSED/ASHAMED","9 - OTHERS, SPECIFY:____"))
hpq$section_o1$o08d_violence_fct <- factor(hpq$section_o1$o08d_violence,levels = c(1,2,3,4,5,9),labels = c("1 - THREATENED","2 - AFRAID","3 - NO FINANCIAL SUPPORT","4 - THINKS NO ONE WOULD LISTEN/BELIEVE","5 - EMBARRASSED/ASHAMED","9 - OTHERS, SPECIFY:____"))
hpq$section_o1$o08e_sxoff_fct <- factor(hpq$section_o1$o08e_sxoff,levels = c(1,2,3,4,5,9),labels = c("1 - THREATENED","2 - AFRAID","3 - NO FINANCIAL SUPPORT","4 - THINKS NO ONE WOULD LISTEN/BELIEVE","5 - EMBARRASSED/ASHAMED","9 - OTHERS, SPECIFY:____"))
hpq$section_o1$o08f_fraud_fct <- factor(hpq$section_o1$o08f_fraud,levels = c(1,2,3,4,5,9),labels = c("1 - THREATENED","2 - AFRAID","3 - NO FINANCIAL SUPPORT","4 - THINKS NO ONE WOULD LISTEN/BELIEVE","5 - EMBARRASSED/ASHAMED","9 - OTHERS, SPECIFY:____"))
hpq$section_o1$o08g_corrupt_fct <- factor(hpq$section_o1$o08g_corrupt,levels = c(1,2,3,4,5,9),labels = c("1 - THREATENED","2 - AFRAID","3 - NO FINANCIAL SUPPORT","4 - THINKS NO ONE WOULD LISTEN/BELIEVE","5 - EMBARRASSED/ASHAMED","9 - OTHERS, SPECIFY:____"))
hpq$section_o1$o08i_vehtheft_fct <- factor(hpq$section_o1$o08i_vehtheft,levels = c(1,2,3,4,5,9),labels = c("1 - THREATENED","2 - AFRAID","3 - NO FINANCIAL SUPPORT","4 - THINKS NO ONE WOULD LISTEN/BELIEVE","5 - EMBARRASSED/ASHAMED","9 - OTHERS, SPECIFY:____"))
hpq$section_o1$o08j_housbreak_fct <- factor(hpq$section_o1$o08j_housbreak,levels = c(1,2,3,4,5,9),labels = c("1 - THREATENED","2 - AFRAID","3 - NO FINANCIAL SUPPORT","4 - THINKS NO ONE WOULD LISTEN/BELIEVE","5 - EMBARRASSED/ASHAMED","9 - OTHERS, SPECIFY:____"))
hpq$section_o1$o08k_vandalism_fct <- factor(hpq$section_o1$o08k_vandalism,levels = c(1,2,3,4,5,9),labels = c("1 - THREATENED","2 - AFRAID","3 - NO FINANCIAL SUPPORT","4 - THINKS NO ONE WOULD LISTEN/BELIEVE","5 - EMBARRASSED/ASHAMED","9 - OTHERS, SPECIFY:____"))
hpq$section_o1$o08z_oth_fct <- factor(hpq$section_o1$o08z_oth,levels = c(1,2,3,4,5,9),labels = c("1 - THREATENED","2 - AFRAID","3 - NO FINANCIAL SUPPORT","4 - THINKS NO ONE WOULD LISTEN/BELIEVE","5 - EMBARRASSED/ASHAMED","9 - OTHERS, SPECIFY:____"))

