hpq$section_g_new$g01_agriact_fct <- factor(hpq$section_g_new$g01_agriact,levels = c(1,2,3),labels = c("1 - AGRICULTURAL LAND/PARCEL","2 - HYDROPONICS","3 - URBAN GARDENING/ROOFTOP GARDENING"))
hpq$section_g_new$g11_1_hhengage_fct <- factor(hpq$section_g_new$g11_1_hhengage,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_g_new$g23_crop3yrs_fct <- factor(hpq$section_g_new$g23_crop3yrs,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g_new$g24_hrvest_fct <- factor(hpq$section_g_new$g24_hrvest,levels = c(1,2,3),labels = c("1 - Decrease","2 - Increase","3 - Remain the same"))
hpq$section_g_new$g25_reasondec_fct <- factor(hpq$section_g_new$g25_reasondec,levels = c(1,2,3,4,5,6,7,8,9,99),labels = c("01 - AFFECTED BY DROUGHT","02 - AFFECTED BY TYPHOON","03 - AFFECTED BY FLOOD","04 - AFFECTED BY PESTS","05 - DECREASE IN THE SUPPLY OF WATER FROM IRRIGATION SYSTEM","06 - PLANT/CROP DISEASES","07 - INCREASE IN THE COST OF FARM INPUTS SUCH AS SEEDS, FERTILIZER, PESTICIDES, ETC.","08 - DECREASE IN LAND AREA","09 - CHANGED IN THE PRIMARY OCCUPATION OF MEMBER","99 - OTHERS, SPECIFY"))
hpq$section_g_new$g30_lvstckpltry3yrs_fct <- factor(hpq$section_g_new$g30_lvstckpltry3yrs,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_g_new$g31_decrease3yrs_fct <- factor(hpq$section_g_new$g31_decrease3yrs,levels = c(1,2,3),labels = c("1 - DECREASE","2 - INCREASE","3 - REMAIN THE SAME"))
hpq$section_g_new$g32_reasondec_fct <- factor(hpq$section_g_new$g32_reasondec,levels = c(1,2,3,4,5,6,9),labels = c("1 - STRICKEN WITH DISEASES (SWINE FLU, BIRD FLU, FOOT AND MOUTH DISEASE)","2 - AFFECTED BY TYPHOON","3 - AFFECTED BY FLOOD","4 - AFFECTED BY EXTREME HOT WEATHER CONDITION","5 - INCREASE IN COST OF INPUTS (FEEDS, CHICKS, ETC.)","6 - DECREASE IN LAND HOLDING","9 - OTHERS, SPECIFY"))
hpq$section_g_new$g43_aqua3year_fct <- factor(hpq$section_g_new$g43_aqua3year,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g_new$g44_aquadec_fct <- factor(hpq$section_g_new$g44_aquadec,levels = c(1,2,3),labels = c("1 - DECREASE","2 - INCREASE","3 - REMAIN THE SAME"))
hpq$section_g_new$g45_reasondec_fct <- factor(hpq$section_g_new$g45_reasondec,levels = c(1,2,3,4,5,6,9),labels = c("1 - AFFECTED BY NATURAL CALAMITIES (TYPHOONS, FLOODS, SOIL EROSIONS, EXCESSIVE HEAT, ETC.)","2 - SUDDEN CHANGE OF WEATHER CONDITIONS","3 - POLLUTION/CONTAMINATION","4 - PESTS AND DISEASES","5 - HIGH COST OF MATERIAL INPUTS","6 - COMPETITION WITH IMPORTED SPECIES","9 - OTHERS, SPECIFY"))
hpq$section_g_new$g47_bove_fct <- factor(hpq$section_g_new$g47_bove,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g_new$g51_fishops1_fct <- factor(hpq$section_g_new$g51_fishops1,levels = c(1,2,3),labels = c("1 - INLAND WATERS ONLY","2 - MARINE WATERS ONLY","3 - INLAND AND MARINE WATERS"))
hpq$section_g_new$g51_fishops_fct <- factor(hpq$section_g_new$g51_fishops,levels = c(1,2,3),labels = c("1 - INLAND WATERS ONLY","2 - MARINE WATERS ONLY","3 - INLAND AND MARINE WATERS"))
hpq$section_g_new$g54_fsh3yrs_fct <- factor(hpq$section_g_new$g54_fsh3yrs,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g_new$g55_hhfish_fct <- factor(hpq$section_g_new$g55_hhfish,levels = c(1,2,3),labels = c("1 - DECREASE","2 - INCREASE","3 - REMAIN THE SAME"))
hpq$section_g_new$g56_reasondec_fct <- factor(hpq$section_g_new$g56_reasondec,levels = c(1,2,3,4,5,6,7,8,9,10,99),labels = c("01 - OCCURRENCE OF CORAL BLEACHING","02 - OCCURRENCE OF FISH KILL","03 - OCCURRENCE OF OIL SPILL AND OTHER KINDS OF POLLUTION","04 - FREQUENT OCCURRENCE OF TYPHOONS","05 - DECREASE IN FISHING AREA DUE TO GOVERNMENT RESTRICTIONS","06 - DECREASE IN FISHING AREA DUE TO COMPETITION","07 - DECREASE IN FISHES/FISH STOCK","08 - LESS FREQUENT FISHING BECAUSE OF THE INCREASE IN FUEL PRICES AND OTHER EXPENSES","09 - SHIFT TO OTHER FORMS OF LIVELIHOOD/EMPLOYMENT/BUSINESS","10 - MAJOR DAMAGE TO BANCA/VESSEL","99 - OTHERS, SPECIFY"))

hpq$section_g1_new$g03_prclloc_fct <- factor(hpq$section_g1_new$g03_prclloc,levels = c(1,2,3),labels = c("1 - Within the barangay","2 - Outside the barangay but within the city/municipality","3 - Outside the barangay and city/municipality"))
hpq$section_g1_new$g03_1_prclactivity_fct <- factor(hpq$section_g1_new$g03_1_prclactivity,levels = c(1,2,3),labels = c("1 - CROP FARMING","2 - LIVESTOCK AND POULTRY","3 - BOTH CROP FARMING AND LIVESTOCK AND POULTRY"))
hpq$section_g1_new$g04_prcltenure_fct <- factor(hpq$section_g1_new$g04_prcltenure,levels = c(1,2,3,4,5,6,7,8,98,99),labels = c("01 - FULLY OWNED","02 - OWNER-LIKE POSSESSION (NOT CBFMA/STEWARDSHIP OR OWNERSHIP DOCUMENT UNKNOWN TO RESPONDENT)","03 - TENANTED","04 - LEASED/RENTED","05 - RENT-FREE","06 - OWNED UNDER CERTIFICATE OF LAND TRANSFER (CLT) OR CERTIFICATE OF LAND OWNERSHIP AWARD (CLOA)","07 - HELD UNDER CERTIFICATE OF ANCESTRAL DOMAIN TITLE/CERTIFICATE OF ANCESTRAL LAND TITLE (CADT/CALT)","08 - HELD UNDER COMMUNITY-BASED FOREST MANAGEMENT AGREEMENT (CBFMA)/STEWARDSHIP)","98 - DON'T KNOW","99 - OTHERS, SPECIFY"))
hpq$section_g1_new$g5_irri_fct <- factor(hpq$section_g1_new$g5_irri,levels = c(1,2,8),labels = c("1 - Yes","2 - No","8 - Don't Know"))
hpq$section_g1_new$g6_irristat_fct <- factor(hpq$section_g1_new$g6_irristat,levels = c(1,2),labels = c("1 - FULLY IRRIGATED","2 - PARTIALLY IRRIGATED"))
hpq$section_g1_new$g7_rainfed_fct <- factor(hpq$section_g1_new$g7_rainfed,levels = c(1,2),labels = c("1 - RAINFED UPLAND","2 - RAINFED LOWLAND"))
hpq$section_g1_new$g8_prclarea1_fct <- factor(hpq$section_g1_new$g8_prclarea1,levels = c(1,2),labels = c("Square Meter","Hectare"))
hpq$section_g1_new$g12a_agrimain_grwcrps_fct <- factor(hpq$section_g1_new$g12a_agrimain_grwcrps,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g12b_agrimain_lvstckpltry_fct <- factor(hpq$section_g1_new$g12b_agrimain_lvstckpltry,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g12c_agrimain_aquacltr_fct <- factor(hpq$section_g1_new$g12c_agrimain_aquacltr,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g12d_agrimain_fshcptr_fct <- factor(hpq$section_g1_new$g12d_agrimain_fshcptr,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g12e_agrimain_gleaning_fct <- factor(hpq$section_g1_new$g12e_agrimain_gleaning,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g12f_agrimain_renting_fct <- factor(hpq$section_g1_new$g12f_agrimain_renting,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g12z_otheragrimain_fct <- factor(hpq$section_g1_new$g12z_otheragrimain,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g13_typengage_grownlvstck_fct <- factor(hpq$section_g1_new$g13_typengage_grownlvstck,levels = c(1,2,3,4,5),labels = c("1 - OPERATOR IN OWN HOUSEHOLD FARM","2 - UNPAID HOUSEHOLD MEMBERS WORKING IN OWN HOUSEHOLD FARM","3 - FARM LABORER/WORKER (PAID) IN OWN HOUSEHOLD FARM","4 - HIRED MANAGER OF ANOTHER HOUSEHOLD FARM OR ESTABLISHMENT/ENTERPRISE/INSTITUTION AGRICULTURAL HOLDING","5 - FARM LABORER/WORKER IN ANOTHER HOUSEHOLD FARM OR ESTABLISHMENT/ENTERPRISE/INSTITUTION AGRICULTURAL HOLDING"))
hpq$section_g1_new$g14a_daytoday_fct <- factor(hpq$section_g1_new$g14a_daytoday,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g14b_landprep_fct <- factor(hpq$section_g1_new$g14b_landprep,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g14c_plantortransplant_fct <- factor(hpq$section_g1_new$g14c_plantortransplant,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g14d_culti_fct <- factor(hpq$section_g1_new$g14d_culti,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g14e_harvestrthresh_fct <- factor(hpq$section_g1_new$g14e_harvestrthresh,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g14f_feeding_fct <- factor(hpq$section_g1_new$g14f_feeding,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g14z_oth_fct <- factor(hpq$section_g1_new$g14z_oth,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g15_typengage_aquanfshnglean_fct <- factor(hpq$section_g1_new$g15_typengage_aquanfshnglean,levels = c(1,2,3,4,5),labels = c("1 - OPERATOR-OWNER OF OWN HOUSEHOLD FISHERY ACTIVITY","2 - HIRED MANAGER IN ANOTHER HOUSEHOLD FISHERY ACTIVITY OR ESTABLISHMENT/ENTERPRISE/INSTITUTION FISHERY BUSINESS","3 - LABORER/WORKER (PAID) IN OWN HOUSEHOLD FISHERY ACTIVITY","4 - UNPAID HOUSEHOLD MEMBER WORKING IN OWN HOUSEHOLD FISHERY ACTIVITY","5 - LABORER/WORKER IN ANOTHER HOUSEHOLD FISHERY ACTIVITY OR ESTABLISHMENT/ENTERPRISE/INSTITUTION FISHERY BUSINESS"))
hpq$section_g1_new$g16a_daytoday_fct <- factor(hpq$section_g1_new$g16a_daytoday,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g16z_oth_fct <- factor(hpq$section_g1_new$g16z_oth,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g17_agriorgmem_fct <- factor(hpq$section_g1_new$g17_agriorgmem,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g19a_typsyshydro_fct <- factor(hpq$section_g1_new$g19a_typsyshydro,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g19b_typsyshydro_fct <- factor(hpq$section_g1_new$g19b_typsyshydro,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g19c_typsyshydro_fct <- factor(hpq$section_g1_new$g19c_typsyshydro,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g19d_typsyshydro_fct <- factor(hpq$section_g1_new$g19d_typsyshydro,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g19e_typsyshydro_fct <- factor(hpq$section_g1_new$g19e_typsyshydro,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g19f_typsyshydro_fct <- factor(hpq$section_g1_new$g19f_typsyshydro,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g19z_typsyshydro_fct <- factor(hpq$section_g1_new$g19z_typsyshydro,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g27a_carabao_fct <- factor(hpq$section_g1_new$g27a_carabao,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g27b_cattle_fct <- factor(hpq$section_g1_new$g27b_cattle,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g27c_goat_fct <- factor(hpq$section_g1_new$g27c_goat,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g27d_swine_fct <- factor(hpq$section_g1_new$g27d_swine,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g27e_chicken_fct <- factor(hpq$section_g1_new$g27e_chicken,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g27f_duck_fct <- factor(hpq$section_g1_new$g27f_duck,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g27g_horse_fct <- factor(hpq$section_g1_new$g27g_horse,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g27h_sheep_fct <- factor(hpq$section_g1_new$g27h_sheep,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g27i_rabbit_fct <- factor(hpq$section_g1_new$g27i_rabbit,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g27j_dogs_fct <- factor(hpq$section_g1_new$g27j_dogs,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g27z_oth_fct <- factor(hpq$section_g1_new$g27z_oth,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_g1_new$g36_aquafrmloc_fct <- factor(hpq$section_g1_new$g36_aquafrmloc,levels = c(1,2,3),labels = c("1 - WITHIN THE BARANGAY","2 - OUTSIDE THE BARANGAY BUT WITHIN THE CITY/MUNICIPALITY","3 - OUTSIDE THE BARANGAY AND CITY/MUNICIPALITY"))
hpq$section_g1_new$g37_typeofaqua_fct <- factor(hpq$section_g1_new$g37_typeofaqua,levels = c(1,2,3,4,5,6,7,9),labels = c("1 - FISHPOND","2 - FISH TANK","3 - FISH PEN","4 - FISH CAGES","5 - SEAWEED FARM","6 - MUSSEL FARM","7 - OYSTER (TALABA) FARM","9 - OTHERS, SPECIFY"))
hpq$section_g1_new$g39_aquawtrenvi_fct <- factor(hpq$section_g1_new$g39_aquawtrenvi,levels = c(1,2,3),labels = c("1 - FRESH WATER","2 - BRACKISH WATER","3 - MARINE WATER"))
hpq$section_g1_new$g40_aquatenure_fct <- factor(hpq$section_g1_new$g40_aquatenure,levels = c(1,2,3,4,5,6,7,8,9,10,99),labels = c("01 - OWNED","02 - OWNED-LIKE","03 - GOVERNMENT-OWNED WITH FISHPOND LEASE AGREEMENT (FLA)","04 - GOVERNMENT-OWNED WITHOUT FISHPOND LEASE AGREEMENT (FLA)","05 - GOVERNMENT-OWNED WITH GRATUITOUS PERMIT","06 - GOVERNMENT-OWNED WITH CIT/MUNICIPAL LICENSE","07 - LESSEE/RENTED","08 - SUB-LESSEE","09 - SUB-SUB LESSEE","10 - RENT-FREE","99 - OTHERS, SPECIFY"))
hpq$section_g1_new$g49_ownboat_fct <- factor(hpq$section_g1_new$g49_ownboat,levels = c(1,2),labels = c("1 - OWNED","2 - NOT OWNED/RENTED"))
hpq$section_g1_new$g50_typeboat_fct <- factor(hpq$section_g1_new$g50_typeboat,levels = c(1,2,3,4),labels = c("1 - BOAT WITH ENGINE AND OUTRIGGER","2 - BOAT WITH ENGINE BUT WITHOUT OUTRIGGER","3 - BOAT WITHOUT ENGINE BUT WITH OUTRIGGER","4 - BOAT WITHOUT ENGINE AND OUTRIGGER"))
hpq$section_g1_new$g16b_pondprep_fct <- factor(hpq$section_g1_new$g16b_pondprep,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_g1_new$g16c_stocking_fct <- factor(hpq$section_g1_new$g16c_stocking,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_g1_new$g16d_feeding_fct <- factor(hpq$section_g1_new$g16d_feeding,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_g1_new$g16e_watrmngt_fct <- factor(hpq$section_g1_new$g16e_watrmngt,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_g1_new$g16f_pondmntnce_fct <- factor(hpq$section_g1_new$g16f_pondmntnce,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_g1_new$g16g_harvesting_fct <- factor(hpq$section_g1_new$g16g_harvesting,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_g1_new$g16h_munfishing_fct <- factor(hpq$section_g1_new$g16h_munfishing,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_g1_new$g16i_gleaning_fct <- factor(hpq$section_g1_new$g16i_gleaning,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_g1_new$g16j_comfishing_fct <- factor(hpq$section_g1_new$g16j_comfishing,levels = c(1,2),labels = c("1 - YES","2 - NO"))
