hpq$section_f$f01_foodconsum_fct <- factor(hpq$section_f$f01_foodconsum, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_f$f02_afishing_fct <- factor(hpq$section_f$f02_afishing, levels = c(1, 2), labels = c("1 - YES", "2 - NO"))
hpq$section_f$f02_blogging_fct <- factor(hpq$section_f$f02_blogging, levels = c(1, 2), labels = c("1 - YES", "2 - NO"))
hpq$section_f$f02_chunting_fct <- factor(hpq$section_f$f02_chunting, levels = c(1, 2), labels = c("1 - YES", "2 - NO"))
hpq$section_f$f02_dfarming_fct <- factor(hpq$section_f$f02_dfarming, levels = c(1, 2), labels = c("1 - YES", "2 - NO"))
hpq$section_f$f02_eraising_fct <- factor(hpq$section_f$f02_eraising, levels = c(1, 2), labels = c("1 - YES", "2 - NO"))
hpq$section_f$f03_crop_fct <- factor(hpq$section_f$f03_crop, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_f$f03_livestock_fct <- factor(hpq$section_f$f03_livestock, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_f$f03_fish_fct <- factor(hpq$section_f$f03_fish, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_f$f03_forest_fct <- factor(hpq$section_f$f03_forest, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_f$f03_mining_fct <- factor(hpq$section_f$f03_mining, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_f$f03_manufac_fct <- factor(hpq$section_f$f03_manufac, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_f$f03_electric_fct <- factor(hpq$section_f$f03_electric, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_f$f03_water_fct <- factor(hpq$section_f$f03_water, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_f$f03_construct_fct <- factor(hpq$section_f$f03_construct, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_f$f03_wholesale_fct <- factor(hpq$section_f$f03_wholesale, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_f$f03_transport_fct <- factor(hpq$section_f$f03_transport, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_f$f03_comm_fct <- factor(hpq$section_f$f03_comm, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_f$f03_accom_fct <- factor(hpq$section_f$f03_accom, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_f$f03_infocomm_fct <- factor(hpq$section_f$f03_infocomm, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_f$f03_fin_fct <- factor(hpq$section_f$f03_fin, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_f$f03_realesta_fct <- factor(hpq$section_f$f03_realesta, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_f$f03_profbus_fct <- factor(hpq$section_f$f03_profbus, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_f$f03_educ_fct <- factor(hpq$section_f$f03_educ, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_f$f03_humsoc_fct <- factor(hpq$section_f$f03_humsoc, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_f$f03_admin_fct <- factor(hpq$section_f$f03_admin, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_f$f03_artenrec_fct <- factor(hpq$section_f$f03_artenrec, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_f$f03_oth_fct <- factor(hpq$section_f$f03_oth, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_f1$f06_entact_fct <- factor(hpq$section_f1$f06_entact, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_f1$f07_socmed_fct <- factor(hpq$section_f1$f07_socmed, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_f1$f09_month_fct <- factor(hpq$section_f1$f09_month, levels = c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M"), labels = c("A - JULY 2021", "B - AUGUST 2021", "C - SEPTEMBER 2021", "D - OCTOBER 2021", "E - NOVEMBER 2021", "F - DECEMBER 2021", "G - JANUARY 2022", "H - FEBRUARY 2022", "I - MARCH 2022", "J - APRIL 2022", "K - MAY 2022", "L - JUNE 2022", "M - ALL MONTHS (FROM JULY 2021 TO JUNE 2022)"))
hpq$section_f1$f11_gov_fct <- factor(hpq$section_f1$f11_gov, levels = c("A", "B", "C", "D", "E", "F", "X"), labels = c("A - BARANGAY LGU", "B - CITY/MUNICIPAL LGU", "C - DTI", "D - BIR", "E - OTHER GOVERNMENT AGENCY", "F - NOT REGISTERED", "X - DON'T KNOW"))
hpq$section_f1$f06_entact_fct <- factor(hpq$section_f1$f06_entact,levels = c(1,2),labels = c("1 - Yes", "2 - No"))
hpq$section_f1$f07_socmed_fct <- factor(hpq$section_f1$f07_socmed,levels = c(1,2),labels = c("1 - Yes", "2 - No"))
hpq$section_f1$f09_month_fct <- factor(hpq$section_f1$f09_month,levels = c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M"), labels = c("A - JULY 2021", "B - AUGUST 2021", "C - SEPTEMBER 2021", "D - OCTOBER 2021", "E - NOVEMBER 2021", "F - DECEMBER 2021", "G - JANUARY 2022", "H - FEBRUARY 2022", "I - MARCH 2022", "J - APRIL 2022", "K - MAY 2022", "L - JUNE 2022", "M - ALL MONTHS (FROM JULY 2021 TO JUNE 2022)"))
hpq$section_f1$f11_gov_fct <- factor(hpq$section_f1$f11_gov,levels = c("A", "B", "C", "D", "E", "F", "X"),labels = c("A - BARANGAY LGU", "B - CITY/MUNICIPAL LGU", "C - DTI", "D - BIR", "E - OTHER GOVERNMENT AGENCY", "F - NOT REGISTERED", "X - DON'T KNOW"))
