hpq$section_k$k01a_bank_fct <- factor(hpq$section_k$k01a_bank,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k01b_digitalbank_fct <- factor(hpq$section_k$k01b_digitalbank,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k01c_emoney_fct <- factor(hpq$section_k$k01c_emoney,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k01d_nsslanonstock_fct <- factor(hpq$section_k$k01d_nsslanonstock,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k01e_coop_fct <- factor(hpq$section_k$k01e_coop,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k01f_microfin_fct <- factor(hpq$section_k$k01f_microfin,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k01z_oth_fct <- factor(hpq$section_k$k01z_oth,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k02a_rsnnofinacct_fct <- factor(hpq$section_k$k02a_rsnnofinacct,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k02b_rsnnofinacct_fct <- factor(hpq$section_k$k02b_rsnnofinacct,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k02c_rsnnofinacct_fct <- factor(hpq$section_k$k02c_rsnnofinacct,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k02d_rsnnofinacct_fct <- factor(hpq$section_k$k02d_rsnnofinacct,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k02e_rsnnofinacct_fct <- factor(hpq$section_k$k02e_rsnnofinacct,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k02f_rsnnofinacct_fct <- factor(hpq$section_k$k02f_rsnnofinacct,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k02g_rsnnofinacct_fct <- factor(hpq$section_k$k02g_rsnnofinacct,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k02h_rsnnofinacct_fct <- factor(hpq$section_k$k02h_rsnnofinacct,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k02i_rsnnofinacct_fct <- factor(hpq$section_k$k02i_rsnnofinacct,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k02j_rsnnofinacct_fct <- factor(hpq$section_k$k02j_rsnnofinacct,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k02z_rsnnofinacct_fct <- factor(hpq$section_k$k02z_rsnnofinacct,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k03_educ_fct <- factor(hpq$section_k$k03_educ,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k03_travel_fct <- factor(hpq$section_k$k03_travel,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k03_emergency_fct <- factor(hpq$section_k$k03_emergency,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k03_savbusiness_fct <- factor(hpq$section_k$k03_savbusiness,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k03_event_fct <- factor(hpq$section_k$k03_event,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k03_invest_fct <- factor(hpq$section_k$k03_invest,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k03_savoth_fct <- factor(hpq$section_k$k03_savoth,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k03_ebanking_fct <- factor(hpq$section_k$k03_ebanking,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k03_debit_fct <- factor(hpq$section_k$k03_debit,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k03_check_fct <- factor(hpq$section_k$k03_check,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k03_pos_fct <- factor(hpq$section_k$k03_pos,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k03_bills_fct <- factor(hpq$section_k$k03_bills,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k03_onlineshop_fct <- factor(hpq$section_k$k03_onlineshop,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k03_loanpayment_fct <- factor(hpq$section_k$k03_loanpayment,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k03_benefits_fct <- factor(hpq$section_k$k03_benefits,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k03_salary_fct <- factor(hpq$section_k$k03_salary,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k03_pension_fct <- factor(hpq$section_k$k03_pension,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k03_loanreceipt_fct <- factor(hpq$section_k$k03_loanreceipt,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k03_allowance_fct <- factor(hpq$section_k$k03_allowance,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k03_businessop_fct <- factor(hpq$section_k$k03_businessop,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k03_remittance_fct <- factor(hpq$section_k$k03_remittance,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k03_others <- factor(hpq$section_k$k03_others,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k04_otherform_fct <- factor(hpq$section_k$k04_otherform,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k05a_where_fct <- factor(hpq$section_k$k05a_where,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k05b_where_fct <- factor(hpq$section_k$k05b_where,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k05c_where_fct <- factor(hpq$section_k$k05c_where,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k05d_where_fct <- factor(hpq$section_k$k05d_where,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k05e_where_fct <- factor(hpq$section_k$k05e_where,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k05z_where_fct <- factor(hpq$section_k$k05z_where,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k06a_rsnnosavings_fct <- factor(hpq$section_k$k06a_rsnnosavings,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k06b_rsnnosavings_fct <- factor(hpq$section_k$k06b_rsnnosavings,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k06c_rsnnosavings_fct <- factor(hpq$section_k$k06c_rsnnosavings,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k06d_rsnnosavings_fct <- factor(hpq$section_k$k06d_rsnnosavings,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k06z_rsnnosavings_fct <- factor(hpq$section_k$k06z_rsnnosavings,levels = c(1,2),labels = c("1 - YES","2 - NO"))
hpq$section_k$k07_loan_fct <- factor(hpq$section_k$k07_loan,levels = c(1,2,8,9),labels = c("1 - YES","2 - NO","8 - DON'T KNOW","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k08a_bank_fct <- factor(hpq$section_k$k08a_bank,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER/DON'T KNOW"))
hpq$section_k$k08b_nssla_fct <- factor(hpq$section_k$k08b_nssla,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER/DON'T KNOW"))
hpq$section_k$k08c_coop_fct <- factor(hpq$section_k$k08c_coop,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER/DON'T KNOW"))
hpq$section_k$k08d_microfin_fct <- factor(hpq$section_k$k08d_microfin,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER/DON'T KNOW"))
hpq$section_k$k08e_traditional_fct <- factor(hpq$section_k$k08e_traditional,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER/DON'T KNOW"))
hpq$section_k$k08f_online_fct <- factor(hpq$section_k$k08f_online,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER/DON'T KNOW"))
hpq$section_k$k08g_pawnshop_fct <- factor(hpq$section_k$k08g_pawnshop,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER/DON'T KNOW"))
hpq$section_k$k08h_govtinstitution_fct <- factor(hpq$section_k$k08h_govtinstitution,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER/DON'T KNOW"))
hpq$section_k$k08i_famrelfrnds_fct <- factor(hpq$section_k$k08i_famrelfrnds,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER/DON'T KNOW"))
hpq$section_k$k08j_informal_fct <- factor(hpq$section_k$k08j_informal,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER/DON'T KNOW"))
hpq$section_k$k08k_advance_fct <- factor(hpq$section_k$k08k_advance,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER/DON'T KNOW"))
hpq$section_k$k08l_inhousefin_fct <- factor(hpq$section_k$k08l_inhousefin,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER/DON'T KNOW"))
hpq$section_k$k08z_others_fct <- factor(hpq$section_k$k08z_others,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER/DON'T KNOW"))
hpq$section_k$k09a_business_fct <- factor(hpq$section_k$k09a_business,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k09b_educ_fct <- factor(hpq$section_k$k09b_educ,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k09c_travel_fct <- factor(hpq$section_k$k09c_travel,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k09d_medical_fct <- factor(hpq$section_k$k09d_medical,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k09e_dailyneeds_fct <- factor(hpq$section_k$k09e_dailyneeds,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k09f_vehicle_fct <- factor(hpq$section_k$k09f_vehicle,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k09g_realestate_fct <- factor(hpq$section_k$k09g_realestate,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k09h_loan_fct <- factor(hpq$section_k$k09h_loan,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k09i_appliance_fct <- factor(hpq$section_k$k09i_appliance,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k09j_insurance_fct <- factor(hpq$section_k$k09j_insurance,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k09k_events_fct <- factor(hpq$section_k$k09k_events,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k09z_others_fct <- factor(hpq$section_k$k09z_others,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k10a_life_fct <- factor(hpq$section_k$k10a_life,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k10b_accident_fct <- factor(hpq$section_k$k10b_accident,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k10c_health_fct <- factor(hpq$section_k$k10c_health,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k10d_combination_fct <- factor(hpq$section_k$k10d_combination,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k10e_fire_fct <- factor(hpq$section_k$k10e_fire,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k10f_vehicle_fct <- factor(hpq$section_k$k10f_vehicle,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k10g_micro_fct <- factor(hpq$section_k$k10g_micro,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k10h_crop_fct <- factor(hpq$section_k$k10h_crop,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k10i_livepoul_fct <- factor(hpq$section_k$k10i_livepoul,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k10j_fisheries_fct <- factor(hpq$section_k$k10j_fisheries,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
hpq$section_k$k10z_oth_fct <- factor(hpq$section_k$k10z_oth,levels = c(1,2,9),labels = c("1 - YES","2 - NO","9 - PREFER NOT TO ANSWER"))
