hpq$section_m$m01_tyhhresidence_fct <-factor(hpq$section_m$m01_tyhhresidence,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m02a_tyhhexp_fct <-factor(hpq$section_m$m02a_tyhhexp,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m02b_tyhhexp_fct <-factor(hpq$section_m$m02b_tyhhexp,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m02c_tyhhexp_fct <-factor(hpq$section_m$m02c_tyhhexp,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m02d_tyhhexp_fct <-factor(hpq$section_m$m02d_tyhhexp,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m02e_tyhhexp_fct <-factor(hpq$section_m$m02e_tyhhexp,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m03_preason_fct <-factor(hpq$section_m$m03_preason,levels = c(1,2,3,4,5,6,9),labels = c("1 - DROUGHT/SUMMER SEASON","2 - BROKEN FAUCET/PUMP","3 - LOWER WATER LEVEL IN THE DAM","4 - LESS FREQUENT DELIVERY OF TANKER TRUCK/PEDDLER","5 - INCREASE IN NUMBER OF CONSUMERS","6 - RAIN/STORM/BAD WEATHER/FLOODING","9 - OTHERS, SPECIFY: _______"))
hpq$section_m$m07_evarea_fct <-factor(hpq$section_m$m07_evarea,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m08_tytempevarea_fct <-factor(hpq$section_m$m08_tytempevarea,levels = c(1,2,8),labels = c("1 - Yes","2 - No","8 - Don't Know"))
hpq$section_m$m09_tymreason_fct <-factor(hpq$section_m$m09_tymreason,levels = c(1,2,3,4,5,6,7,8,9,99),labels = c("01 - TYPHOON","02 - FLOOD","03 - DROUGHT","04 - EARTHQUAKE","05 - VOLCANIC ERUPTION","06 - LANDSLIDE/MUDSLIDE","07 - FIRE","08 - EPIDEMIC/PANDEMIC","09 - ARMED CONFLICT","99 - OTHERS, SPECIFY: _____"))
hpq$section_m$m09a_tymreason_fct <-factor(hpq$section_m$m09a_tymreason,levels = c(1:9, 99),labels = c("01 - TYPHOON","02 - FLOOD","03 - DROUGHT","04 - EARTHQUAKE","05 - VOLCANIC ERUPTION","06 - LANDSLIDE/MUDSLIDE","07 - FIRE","08 - EPIDEMIC/PANDEMIC","09 - ARMED CONFLICT","99 - OTHERS, SPECIFY: _____"))
hpq$section_m$m10_tmltemeva_fct <-factor(hpq$section_m$m10_tmltemeva,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m11_stayevarea_fct <-factor(hpq$section_m$m11_stayevarea,levels = c(1,2,3,4,5,6,7,9),labels = c("1 - SCHOOL","2 - CHURCH","3 - COVERED COURT/GYM","4 - RELATIVE?S HOUSE","5 - NEIGHBOR?S OR FRIEND?S HOUSE","6 - BARANGAY HALL","7 - DEDICATED EVACUATION CENTER","9 - OTHERS, SPECIFY: ______"))
hpq$section_m$m13a_negaff_fct <-factor(hpq$section_m$m13a_negaff,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m13b_negaff_fct <-factor(hpq$section_m$m13b_negaff,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m13c_negaff_fct <-factor(hpq$section_m$m13c_negaff,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m13d_negaff_fct <-factor(hpq$section_m$m13d_negaff,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m13e_negaff_fct <-factor(hpq$section_m$m13e_negaff,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m13f_negaff_fct <-factor(hpq$section_m$m13f_negaff,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m13g_negaff_fct <-factor(hpq$section_m$m13g_negaff,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m13h_negaff_fct <-factor(hpq$section_m$m13h_negaff,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m13i_negaff_fct <-factor(hpq$section_m$m13i_negaff,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m13z_negaff_fct <-factor(hpq$section_m$m13z_negaff,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14ta_typhoon_fct <-factor(hpq$section_m$m14ta_typhoon,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14tb_typhoon_fct <-factor(hpq$section_m$m14tb_typhoon,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14tc_typhoon_fct <-factor(hpq$section_m$m14tc_typhoon,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14td_typhoon_fct <-factor(hpq$section_m$m14td_typhoon,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14te_typhoon_fct <-factor(hpq$section_m$m14te_typhoon,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14tf_typhoon_fct <-factor(hpq$section_m$m14tf_typhoon,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14tg_typhoon_fct <-factor(hpq$section_m$m14tg_typhoon,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14th_typhoon_fct <-factor(hpq$section_m$m14th_typhoon,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14ti_typhoon_fct <-factor(hpq$section_m$m14ti_typhoon,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14tz_typhoon_fct <-factor(hpq$section_m$m14tz_typhoon,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14fa_flood_fct <-factor(hpq$section_m$m14fa_flood,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14fb_flood_fct <-factor(hpq$section_m$m14fb_flood,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14fc_flood_fct <-factor(hpq$section_m$m14fc_flood,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14fd_flood_fct <-factor(hpq$section_m$m14fd_flood,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14fe_flood_fct <-factor(hpq$section_m$m14fe_flood,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14ff_flood_fct <-factor(hpq$section_m$m14ff_flood,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14fg_flood_fct <-factor(hpq$section_m$m14fg_flood,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14fh_flood_fct <-factor(hpq$section_m$m14fh_flood,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14fi_flood_fct <-factor(hpq$section_m$m14fi_flood,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14fz_flood_fct <-factor(hpq$section_m$m14fz_flood,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14da_drought_fct <-factor(hpq$section_m$m14da_drought,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14db_drought_fct <-factor(hpq$section_m$m14db_drought,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14dc_drought_fct <-factor(hpq$section_m$m14dc_drought,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14dd_drought_fct <-factor(hpq$section_m$m14dd_drought,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14de_drought_fct <-factor(hpq$section_m$m14de_drought,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14df_drought_fct <-factor(hpq$section_m$m14df_drought,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14dg_drought_fct <-factor(hpq$section_m$m14dg_drought,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14dh_drought_fct <-factor(hpq$section_m$m14dh_drought,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14di_drought_fct <-factor(hpq$section_m$m14di_drought,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14dz_drought_fct <-factor(hpq$section_m$m14dz_drought,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14ea_earthquake_fct <-factor(hpq$section_m$m14ea_earthquake,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14eb_earthquake_fct <-factor(hpq$section_m$m14eb_earthquake,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14ec_earthquake_fct <-factor(hpq$section_m$m14ec_earthquake,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14ed_earthquake_fct <-factor(hpq$section_m$m14ed_earthquake,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14ee_earthquake_fct <-factor(hpq$section_m$m14ee_earthquake,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14ef_earthquake_fct <-factor(hpq$section_m$m14ef_earthquake,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14eg_earthquake_fct <-factor(hpq$section_m$m14eg_earthquake,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14eh_earthquake_fct <-factor(hpq$section_m$m14eh_earthquake,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14ei_earthquake_fct <-factor(hpq$section_m$m14ei_earthquake,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14ez_earthquake_fct <-factor(hpq$section_m$m14ez_earthquake,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14va_volcaniceruption_fct <-factor(hpq$section_m$m14va_volcaniceruption,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14vb_volcaniceruption_fct <-factor(hpq$section_m$m14vb_volcaniceruption,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14vc_volcaniceruption_fct <-factor(hpq$section_m$m14vc_volcaniceruption,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14vd_volcaniceruption_fct <-factor(hpq$section_m$m14vd_volcaniceruption,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14ve_volcaniceruption_fct <-factor(hpq$section_m$m14ve_volcaniceruption,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14vf_volcaniceruption_fct <-factor(hpq$section_m$m14vf_volcaniceruption,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14vg_volcaniceruption_fct <-factor(hpq$section_m$m14vg_volcaniceruption,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14vh_volcaniceruption_fct <-factor(hpq$section_m$m14vh_volcaniceruption,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14vi_volcaniceruption_fct <-factor(hpq$section_m$m14vi_volcaniceruption,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14vz_volcaniceruption_fct <-factor(hpq$section_m$m14vz_volcaniceruption,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14la_landslide_fct <-factor(hpq$section_m$m14la_landslide,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14lb_landslide_fct <-factor(hpq$section_m$m14lb_landslide,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14lc_landslide_fct <-factor(hpq$section_m$m14lc_landslide,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14ld_landslide_fct <-factor(hpq$section_m$m14ld_landslide,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14le_landslide_fct <-factor(hpq$section_m$m14le_landslide,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14lf_landslide_fct <-factor(hpq$section_m$m14lf_landslide,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14lg_landslide_fct <-factor(hpq$section_m$m14lg_landslide,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14lh_landslide_fct <-factor(hpq$section_m$m14lh_landslide,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14li_landslide_fct <-factor(hpq$section_m$m14li_landslide,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14lz_landslide_fct <-factor(hpq$section_m$m14lz_landslide,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14fia_fire_fct <-factor(hpq$section_m$m14fia_fire,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14fib_fire_fct <-factor(hpq$section_m$m14fib_fire,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14fic_fire_fct <-factor(hpq$section_m$m14fic_fire,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14fid_fire_fct <-factor(hpq$section_m$m14fid_fire,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14fie_fire_fct <-factor(hpq$section_m$m14fie_fire,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14fif_fire_fct <-factor(hpq$section_m$m14fif_fire,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14fig_fire_fct <-factor(hpq$section_m$m14fig_fire,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14fih_fire_fct <-factor(hpq$section_m$m14fih_fire,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14fii_fire_fct <-factor(hpq$section_m$m14fii_fire,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14fiz_fire_fct <-factor(hpq$section_m$m14fiz_fire,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14pa_pandemic_fct <-factor(hpq$section_m$m14pa_pandemic,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14pb_pandemic_fct <-factor(hpq$section_m$m14pb_pandemic,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14pc_pandemic_fct <-factor(hpq$section_m$m14pc_pandemic,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14pd_pandemic_fct <-factor(hpq$section_m$m14pd_pandemic,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14pe_pandemic_fct <-factor(hpq$section_m$m14pe_pandemic,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14pf_pandemic_fct <-factor(hpq$section_m$m14pf_pandemic,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14pg_pandemic_fct <-factor(hpq$section_m$m14pg_pandemic,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14ph_pandemic_fct <-factor(hpq$section_m$m14ph_pandemic,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14pi_pandemic_fct <-factor(hpq$section_m$m14pi_pandemic,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14pz_pandemic_fct <-factor(hpq$section_m$m14pz_pandemic,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14aa_armedconflict_fct <-factor(hpq$section_m$m14aa_armedconflict,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14ab_armedconflict_fct <-factor(hpq$section_m$m14ab_armedconflict,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14ac_armedconflict_fct <-factor(hpq$section_m$m14ac_armedconflict,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14ad_armedconflict_fct <-factor(hpq$section_m$m14ad_armedconflict,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14ae_armedconflict_fct <-factor(hpq$section_m$m14ae_armedconflict,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14af_armedconflict_fct <-factor(hpq$section_m$m14af_armedconflict,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14ag_armedconflict_fct <-factor(hpq$section_m$m14ag_armedconflict,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14ah_armedconflict_fct <-factor(hpq$section_m$m14ah_armedconflict,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14ai_armedconflict_fct <-factor(hpq$section_m$m14ai_armedconflict,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14az_armedconflict_fct <-factor(hpq$section_m$m14az_armedconflict,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14oa_others_fct <-factor(hpq$section_m$m14oa_others,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14ob_others_fct <-factor(hpq$section_m$m14ob_others,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14oc_others_fct <-factor(hpq$section_m$m14oc_others,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14od_others_fct <-factor(hpq$section_m$m14od_others,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14oe_others_fct <-factor(hpq$section_m$m14oe_others,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14of_others_fct <-factor(hpq$section_m$m14of_others,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14og_others_fct <-factor(hpq$section_m$m14og_others,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14oh_others_fct <-factor(hpq$section_m$m14oh_others,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14oi_others_fct <-factor(hpq$section_m$m14oi_others,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m14oz_others_fct <-factor(hpq$section_m$m14oz_others,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17ta_typhoon_fct <-factor(hpq$section_m$m17ta_typhoon,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17tb_typhoon_fct <-factor(hpq$section_m$m17tb_typhoon,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17td_typhoon_fct <-factor(hpq$section_m$m17td_typhoon,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17tz_typhoon_fct <-factor(hpq$section_m$m17tz_typhoon,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17fa_flood_fct <-factor(hpq$section_m$m17fa_flood,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17fb_flood_fct <-factor(hpq$section_m$m17fb_flood,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17fc_flood_fct <-factor(hpq$section_m$m17fc_flood,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17fd_flood_fct <-factor(hpq$section_m$m17fd_flood,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17fz_flood_fct <-factor(hpq$section_m$m17fz_flood,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17da_drought_fct <-factor(hpq$section_m$m17da_drought,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17db_drought_fct <-factor(hpq$section_m$m17db_drought,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17dc_drought_fct <-factor(hpq$section_m$m17dc_drought,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17dd_drought_fct <-factor(hpq$section_m$m17dd_drought,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17dz_drought_fct <-factor(hpq$section_m$m17dz_drought,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17ea_earthquake_fct <-factor(hpq$section_m$m17ea_earthquake,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17eb_earthquake_fct <-factor(hpq$section_m$m17eb_earthquake,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17ec_earthquake_fct <-factor(hpq$section_m$m17ec_earthquake,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17ed_earthquake_fct <-factor(hpq$section_m$m17ed_earthquake,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17ez_earthquake_fct <-factor(hpq$section_m$m17ez_earthquake,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17va_eruption_fct <-factor(hpq$section_m$m17va_eruption,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17vb_eruption_fct <-factor(hpq$section_m$m17vb_eruption,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17vc_eruption_fct <-factor(hpq$section_m$m17vc_eruption,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17vd_eruption_fct <-factor(hpq$section_m$m17vd_eruption,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17vz_eruption_fct <-factor(hpq$section_m$m17vz_eruption,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17la_landslide_fct <-factor(hpq$section_m$m17la_landslide,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17lb_landslide_fct <-factor(hpq$section_m$m17lb_landslide,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17lc_landslide_fct <-factor(hpq$section_m$m17lc_landslide,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17ld_landslide_fct <-factor(hpq$section_m$m17ld_landslide,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17lz_landslide_fct <-factor(hpq$section_m$m17lz_landslide,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17fa_fire_fct <-factor(hpq$section_m$m17fa_fire,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17fb_fire_fct <-factor(hpq$section_m$m17fb_fire,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17fc_fire_fct <-factor(hpq$section_m$m17fc_fire,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17fd_fire_fct <-factor(hpq$section_m$m17fd_fire,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17fz_fire_fct <-factor(hpq$section_m$m17fz_fire,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17pa_pandemic_fct <-factor(hpq$section_m$m17pa_pandemic,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17pb_pandemic_fct <-factor(hpq$section_m$m17pb_pandemic,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17pc_pandemic_fct <-factor(hpq$section_m$m17pc_pandemic,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17pd_pandemic_fct <-factor(hpq$section_m$m17pd_pandemic,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17pz_pandemic_fct <-factor(hpq$section_m$m17pz_pandemic,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17aa_armedconflict_fct <-factor(hpq$section_m$m17aa_armedconflict,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17ab_armedconflict_fct <-factor(hpq$section_m$m17ab_armedconflict,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17ac_armedconflict_fct <-factor(hpq$section_m$m17ac_armedconflict,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17ad_armedconflict_fct <-factor(hpq$section_m$m17ad_armedconflict,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17az_armedconflict_fct <-factor(hpq$section_m$m17az_armedconflict,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17oa_others_fct <- factor(hpq$section_m$m17oa_others,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17ob_others_fct <- factor(hpq$section_m$m17ob_others,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17oc_others_fct <- factor(hpq$section_m$m17oc_others,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17od_others_fct <- factor(hpq$section_m$m17od_others,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m17oz_others_fct <- factor(hpq$section_m$m17oz_others,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18ta_typhoon_fct <- factor(hpq$section_m$m18ta_typhoon,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18tb_typhoon_fct <- factor(hpq$section_m$m18tb_typhoon,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18tc_typhoon_fct <- factor(hpq$section_m$m18tc_typhoon,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18td_typhoon_fct <- factor(hpq$section_m$m18td_typhoon,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18te_typhoon_fct <- factor(hpq$section_m$m18te_typhoon,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18tf_typhoon_fct <- factor(hpq$section_m$m18tf_typhoon,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18tg_typhoon_fct <- factor(hpq$section_m$m18tg_typhoon,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18th_typhoon_fct <- factor(hpq$section_m$m18th_typhoon,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18tz_typhoon_fct <- factor(hpq$section_m$m18tz_typhoon,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18fa_flood_fct <- factor(hpq$section_m$m18fa_flood,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18fb_flood_fct <- factor(hpq$section_m$m18fb_flood,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18fc_flood_fct <- factor(hpq$section_m$m18fc_flood,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18fd_flood_fct <- factor(hpq$section_m$m18fd_flood,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18fe_flood_fct <- factor(hpq$section_m$m18fe_flood,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18ff_flood_fct <- factor(hpq$section_m$m18ff_flood,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18fg_flood_fct <- factor(hpq$section_m$m18fg_flood,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18fh_flood_fct <- factor(hpq$section_m$m18fh_flood,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18fz_flood_fct <- factor(hpq$section_m$m18fz_flood,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18da_drought_fct <- factor(hpq$section_m$m18da_drought,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18db_drought_fct <- factor(hpq$section_m$m18db_drought,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18dc_drought_fct <- factor(hpq$section_m$m18dc_drought,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18dd_drought_fct <- factor(hpq$section_m$m18dd_drought,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18de_drought_fct <- factor(hpq$section_m$m18de_drought,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18df_drought_fct <- factor(hpq$section_m$m18df_drought,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18dg_drought_fct <- factor(hpq$section_m$m18dg_drought,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18dh_drought_fct <- factor(hpq$section_m$m18dh_drought,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18dz_drought_fct <- factor(hpq$section_m$m18dz_drought,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18ea_earthquake_fct <- factor(hpq$section_m$m18ea_earthquake,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18eb_earthquake_fct <- factor(hpq$section_m$m18eb_earthquake,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18ec_earthquake_fct <- factor(hpq$section_m$m18ec_earthquake,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18ed_earthquake_fct <- factor(hpq$section_m$m18ed_earthquake,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18ee_earthquake_fct <- factor(hpq$section_m$m18ee_earthquake,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18ef_earthquake_fct <- factor(hpq$section_m$m18ef_earthquake,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18eg_earthquake_fct <- factor(hpq$section_m$m18eg_earthquake,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18eh_earthquake_fct <- factor(hpq$section_m$m18eh_earthquake,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18ez_earthquake_fct <- factor(hpq$section_m$m18ez_earthquake,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18va_eruption_fct <- factor(hpq$section_m$m18va_eruption,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18vb_eruption_fct <- factor(hpq$section_m$m18vb_eruption,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18vc_eruption_fct <- factor(hpq$section_m$m18vc_eruption,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18vd_eruption_fct <- factor(hpq$section_m$m18vd_eruption,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18ve_eruption_fct <- factor(hpq$section_m$m18ve_eruption,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18vf_eruption_fct <- factor(hpq$section_m$m18vf_eruption,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18vg_eruption_fct <- factor(hpq$section_m$m18vg_eruption,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18vh_eruption_fct <- factor(hpq$section_m$m18vh_eruption,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18vz_eruption_fct <- factor(hpq$section_m$m18vz_eruption,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18la_landslide_fct <- factor(hpq$section_m$m18la_landslide,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18lb_landslide_fct <- factor(hpq$section_m$m18lb_landslide,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18lc_landslide_fct <- factor(hpq$section_m$m18lc_landslide,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18ld_landslide_fct <- factor(hpq$section_m$m18ld_landslide,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18le_landslide_fct <- factor(hpq$section_m$m18le_landslide,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18lf_landslide_fct <- factor(hpq$section_m$m18lf_landslide,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18lg_landslide_fct <- factor(hpq$section_m$m18lg_landslide,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18lh_landslide_fct <- factor(hpq$section_m$m18lh_landslide,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18lz_landslide_fct <- factor(hpq$section_m$m18lz_landslide,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18fa_fire_fct <- factor(hpq$section_m$m18fa_fire,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18fb_fire_fct <- factor(hpq$section_m$m18fb_fire,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18fc_fire_fct <- factor(hpq$section_m$m18fc_fire,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18fd_fire_fct <- factor(hpq$section_m$m18fd_fire,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18fe_fire_fct <- factor(hpq$section_m$m18fe_fire,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18ff_fire_fct <- factor(hpq$section_m$m18ff_fire,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18fg_fire_fct <- factor(hpq$section_m$m18fg_fire,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18fh_fire_fct <- factor(hpq$section_m$m18fh_fire,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18fz_fire_fct <- factor(hpq$section_m$m18fz_fire,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18pa_pandemic_fct <- factor(hpq$section_m$m18pa_pandemic,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18pb_pandemic_fct <- factor(hpq$section_m$m18pb_pandemic,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18pc_pandemic_fct <- factor(hpq$section_m$m18pc_pandemic,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18pd_pandemic_fct <- factor(hpq$section_m$m18pd_pandemic,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18pe_pandemic_fct <- factor(hpq$section_m$m18pe_pandemic,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18pf_pandemic_fct <- factor(hpq$section_m$m18pf_pandemic,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18pg_pandemic_fct <- factor(hpq$section_m$m18pg_pandemic,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18ph_pandemic_fct <- factor(hpq$section_m$m18ph_pandemic,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18pz_pandemic_fct <- factor(hpq$section_m$m18pz_pandemic,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18aa_armedconflict_fct <- factor(hpq$section_m$m18aa_armedconflict,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18ab_armedconflict_fct <- factor(hpq$section_m$m18ab_armedconflict,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18ac_armedconflict_fct <- factor(hpq$section_m$m18ac_armedconflict,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18ad_armedconflict_fct <- factor(hpq$section_m$m18ad_armedconflict,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18ae_armedconflict_fct <- factor(hpq$section_m$m18ae_armedconflict,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18af_armedconflict_fct <- factor(hpq$section_m$m18af_armedconflict,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18ag_armedconflict_fct <- factor(hpq$section_m$m18ag_armedconflict,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18ah_armedconflict_fct <- factor(hpq$section_m$m18ah_armedconflict,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18az_armedconflict_fct <- factor(hpq$section_m$m18az_armedconflict,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18oa_other_fct <- factor(hpq$section_m$m18oa_other,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18ob_other_fct <- factor(hpq$section_m$m18ob_other,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18oc_other_fct <- factor(hpq$section_m$m18oc_other,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18od_other_fct <- factor(hpq$section_m$m18od_other,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18oe_other_fct <- factor(hpq$section_m$m18oe_other,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18of_other_fct <- factor(hpq$section_m$m18of_other,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18og_other_fct <- factor(hpq$section_m$m18og_other,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18oh_other_fct <- factor(hpq$section_m$m18oh_other,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m18oz_other_fct <- factor(hpq$section_m$m18oz_other,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m19_diskit_fct <- factor(hpq$section_m$m19_diskit,levels = c(1,2),labels = c("Yes","No"))
hpq$section_m$m20_diskit_fct <- factor(hpq$section_m$m20_diskit,levels = c(1,2),labels = c("Yes","No"))
hpq$section_m$m21_afood_fct <- factor(hpq$section_m$m21_afood,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m21_bmaintenance_fct <- factor(hpq$section_m$m21_bmaintenance,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m21_cclothes_fct <- factor(hpq$section_m$m21_cclothes,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m21_dinfant_fct <- factor(hpq$section_m$m21_dinfant,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m21_emedical_fct <- factor(hpq$section_m$m21_emedical,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m21_fmoney_fct <- factor(hpq$section_m$m21_fmoney,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m21_gimportant_fct <- factor(hpq$section_m$m21_gimportant,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m21_hwater_fct <- factor(hpq$section_m$m21_hwater,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m21_imatcheslighter_fct <- factor(hpq$section_m$m21_imatcheslighter,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m21_jcandle_fct <- factor(hpq$section_m$m21_jcandle,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m21_kbattery_fct <- factor(hpq$section_m$m21_kbattery,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m21_lfacemasks_fct <- factor(hpq$section_m$m21_lfacemasks,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m21_mflashlight_fct <- factor(hpq$section_m$m21_mflashlight,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m21_nradio_fct <- factor(hpq$section_m$m21_nradio,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m21_owhistle_fct <- factor(hpq$section_m$m21_owhistle,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m21_pblanket_fct <- factor(hpq$section_m$m21_pblanket,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m21_qcellphone_fct <- factor(hpq$section_m$m21_qcellphone,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m23_participate_fct <- factor(hpq$section_m$m23_participate,levels = c(1,2),labels = c("Yes","No"))
hpq$section_m$m24a_chair_fct <- factor(hpq$section_m$m24a_chair,levels = c(1,2),labels = c("Yes","No"))
hpq$section_m$m24b_emplo_fct <- factor(hpq$section_m$m24b_emplo,levels = c(1,2),labels = c("Yes","No"))
hpq$section_m$m24c_assembly_fct <- factor(hpq$section_m$m24c_assembly,levels = c(1,2),labels = c("Yes","No"))
hpq$section_m$m24d_comment_fct <- factor(hpq$section_m$m24d_comment,levels = c(1,2),labels = c("Yes","No"))
hpq$section_m$m24z_others_fct <- factor(hpq$section_m$m24z_others,levels = c(1,2),labels = c("Yes","No"))
hpq$section_m$m25_info_fct <- factor(hpq$section_m$m25_info,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m26_prepare_fct <- factor(hpq$section_m$m26_prepare,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m27_cnumber_fct <- factor(hpq$section_m$m27_cnumber,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m28_evac_fct <- factor(hpq$section_m$m28_evac,levels = c(1,2),labels = c("1 - Yes","2 - No"))
hpq$section_m$m21_others_fct <- factor(hpq$section_m$m21_others,levels = c(1,2),labels = c("1 - YES","2 - NO"))
