hpq$section_d$d01_regvoter_fct <- factor(hpq$section_d$d01_regvoter, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_d$d02_votele_fct <- factor(hpq$section_d$d02_votele, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_d$d03_sptime_fct <- factor(hpq$section_d$d03_sptime, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_d$d05_collecting_fct <- factor(hpq$section_d$d05_collecting, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_d$d06_predonated_fct <- factor(hpq$section_d$d06_predonated, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_d$d09_spone_fct <- factor(hpq$section_d$d09_spone, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_d$d10_sptime_fct <- factor(hpq$section_d$d10_sptime, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_d$d13_blvoluteer_fct <- factor(hpq$section_d$d13_blvoluteer, levels = c(1:7), labels = c("1 - BARANGAY TANOD", "2 - BARANGAY HEALTH WORKER (BHW)", "3 - BARANGAY NUTRITION SCHOLAR", "4 - OTHER BARANGAY VOLUNTEER, SPECIFY ___________", "5 - CITY/MUN LGU VOLUNTEER, SPECIFY ___________", "6 - PROVINCIAL LGU VOLUNTEER, SPECIFY ___________", "7 - NOT A BARANGAY OR AN LGU VOLUNTEER"))
hpq$section_d$a05_sex_fct <- factor(hpq$section_d$a05_sex, levels = c(1, 2), labels = c("1 - Male", "2 - Female"))