hpq$section_a$a02_reltohhh_fct <- factor(hpq$section_a$a02_reltohhh, levels = c(1:26), labels = c("Head", "Spouse", "Son", "Daughter", "Stepson", "Stepdaughter", "Son-In-Law", "Daughter-In-Law", "Grandson", "Granddaughte", "Father", "Mother", "Father-In-Law", "Mother-In-Law", "Brother", "Sister", "Brother-In-Law", "Sister-In-Law", "Uncle", "Aunt", "Nephew", "Niece", "Other Relative", "Boarder", "Domestic Helper", "Nonrelative"))
hpq$section_a$a04_reltonucfh_fct <- factor(hpq$section_a$a04_reltonucfh, levels = c(1:10), labels = c("1 - Family head", "2 - Spouse", "3 - Partner", "4 - Son", "5 - Daughter", "6 - Brother", "7 - Sister", "8 - Father", "9 - Mother", "10 - Other Family Member"))
hpq$section_a$a05_sex_fct <- factor(hpq$section_a$a05_sex, levels = c(1, 2), labels = c("1 - Male", "2 - Female"))
hpq$section_a$a08_birthreg_fct <- factor(hpq$section_a$a08_birthreg, levels = c(1, 2, 8), labels = c("1 - Yes", "2 - No", "8 - Don't Know"))
hpq$section_a$a09_mstat_fct <- factor(hpq$section_a$a09_mstat, levels = c(1:8), labels = c("1 - SINGLE", "2 - MARRIED", "3 - COMMON LAW/LIVE-IN", "4 - WIDOWED", "5 - DIVORCED", "6 - SEPARATED", "7 - ANNULLED", "8 - UNKNOWN"))
hpq$section_a$a12_philid_fct <- factor(hpq$section_a$a12_philid, levels = c(1, 2, 8), labels = c("1 - Yes", "2 - No", "8 - Don't Know"))
hpq$section_a$a14_step2_fct <- factor(hpq$section_a$a14_step2, levels = c(1, 2, 8), labels = c("1 - Yes", "2 - No", "8 - Don't Know"))
hpq$section_a$a15_lguid_fct <- factor(hpq$section_a$a15_lguid, levels = c(1, 2, 8), labels = c("1 - Yes", "2 - No", "8 - Don't Know"))
hpq$section_a$a17_solopar_fct <- factor(hpq$section_a$a17_solopar, levels = c(1, 2), labels = c("1 - Yes", "2 - No"))
hpq$section_a$a18_soloid_fct <- factor(hpq$section_a$a18_soloid, levels = c(1, 2, 8), labels = c("1 - Yes", "2 - No", "8 - Don't Know"))
hpq$section_a$a19_sctznidq_fct <- factor(hpq$section_a$a19_sctznidq, levels = c(1, 2, 8), labels = c("1 - Yes", "2 - No", "8 - Don't Know"))
hpq$section_a$a20_diffseeing_fct <- factor(hpq$section_a$a20_diffseeing, levels = c(1:4), labels = c("1 - No, no difficulty", "2 - Yes, some difficulty", "3 - Yes, a lot of difficulty", "4 - Cannot do it at all"))
hpq$section_a$a20_diffhring_fct <- factor(hpq$section_a$a20_diffhring, levels = c(1:4), labels = c("1 - No, no difficulty", "2 - Yes, some difficulty", "3 - Yes, a lot of difficulty", "4 - Cannot do it at all"))
hpq$section_a$a20_diffwalk_fct <- factor(hpq$section_a$a20_diffwalk, levels = c(1:4), labels = c("1 - No, no difficulty", "2 - Yes, some difficulty", "3 - Yes, a lot of difficulty", "4 - Cannot do it at all"))
hpq$section_a$a20_diffremem_fct <- factor(hpq$section_a$a20_diffremem, levels = c(1:4), labels = c("1 - No, no difficulty", "2 - Yes, some difficulty", "3 - Yes, a lot of difficulty", "4 - Cannot do it at all"))
hpq$section_a$a20_diffslfcare_fct <- factor(hpq$section_a$a20_diffslfcare, levels = c(1:4), labels = c("1 - No, no difficulty", "2 - Yes, some difficulty", "3 - Yes, a lot of difficulty", "4 - Cannot do it at all"))
hpq$section_a$a20_diffcomm_fct <- factor(hpq$section_a$a20_diffcomm, levels = c(1:4), labels = c("1 - No, no difficulty", "2 - Yes, some difficulty", "3 - Yes, a lot of difficulty", "4 - Cannot do it at all"))
