run_after_edit: false
use_rdata: false
include_justifiction: false
clear: false
save_by_area: false
convert_to_rdata: false
append_new_record: false
use_pilot_data: false
use_raw_data_from_tablet: false
paths:
  r_path: ''
  rstudio_path: C:\Program Files\RStudio\bin\rstudio.exe
  quarto_path: C:\Program Files\RStudio\bin\quarto\bin\quarto.exe
  rdata_path: >-
    /Users/bhasabdulsamad/Desktop/Apps/rcbms-app/src/main/static/rcbms/data/hpq.Rdata
  before_edit_path: C:\PSA SYSTEMS FOLDER\CBMS-ROLLOUT\HPQ\DOWNLOADED
  after_edit_path: C:\PSA SYSTEMS FOLDER\CBMS-ROLLOUT\HPQ\EDITED
  justification_path: >-
    /Users/bhasabdulsamad/Desktop/Apps/rcbms-app/src/main/static/rcbms/references/justifications.xlsx
  output_path: /Users/bhasabdulsamad/Desktop/Apps/rcbms-app/src/main/static/rcbms/output
  pilot_output_path: >-
    /Users/bhasabdulsamad/Desktop/Apps/rcbms-app/src/main/static/rcbms/scripts/2021-pilot-cbms/output/Inconsistencies
  reference_path: >-
    /Users/bhasabdulsamad/Desktop/Apps/rcbms-app/src/main/static/rcbms/references/dictionary.xlsx
  cspro_path: ''
  csconcat_path: ''
  csexport_path: ''
  pilot_data_path: >-
    /Users/bhasabdulsamad/Desktop/Apps/rcbms-app/src/main/static/rcbms/data/pilot
  pilot_data_dict_path: >-
    /Users/bhasabdulsamad/Desktop/Apps/rcbms-app/src/main/static/rcbms/scripts/2021-pilot-cbms/references/HPQF2_PILOT_DICT.dcf
